const previousDeals = [
  {
    _id: 1,
    name: 'Cadbury Dairy Milk Silk Fruit & Nut Chocolate Bar (Free Cadbury Dairy Milk Chocolate 55 gm) 137 gm',
    description: '',
    price: 299,
    original_price: 375,
    save: '20%',
    bundle: '137 gm',
    imageUrl:
      'https://chaldn.com/_mpimage/cadbury-dairy-milk-silk-fruit-nut-chocolate-bar-free-cadbury-dairy-milk-chocolate-55-gm-137-gm?src=https%3A%2F%2Feggyolk.chaldal.com%2Fapi%2FPicture%2FRaw%3FpictureId%3D127914&q=best&v=1&m=400&webp=1',
    category: 'Food',
    quantity: 1,
    status: 'previous&deal',
    stock: 1000,
  },

  {
    _id: 2,
    name: 'Cadbury Dairy Milk Silk Fruit & Nut Chocolate Bar (Free Cadbury Dairy Milk Chocolate 55 gm) 137 gm',
    description: '',
    price: 299,
    original_price: 375,
    save: '20%',
    bundle: '137 gm',
    imageUrl:
      'https://chaldn.com/_mpimage/cadbury-dairy-milk-chocolate-bar-family-pack-126-gm?src=https%3A%2F%2Feggyolk.chaldal.com%2Fapi%2FPicture%2FRaw%3FpictureId%3D127916&q=best&v=1&m=400&webp=1',
    category: 'Food',
    quantity: 1,
    status: 'previous&deal',
    stock: 1000,
  },
  {
    _id: 3,
    name: 'Saffola Honey (Free Parachute Coconut Oil 100 ml) 500 gm',
    description: '',
    price: 399,
    original_price: 475,
    save: '20%',
    bundle: '500 gm',
    imageUrl:
      'https://chaldn.com/_mpimage/saffola-honey-free-parachute-coconut-oil-100-ml-500-gm?src=https%3A%2F%2Feggyolk.chaldal.com%2Fapi%2FPicture%2FRaw%3FpictureId%3D127482&q=best&v=1&m=400&webp=1',
    category: 'Food',
    quantity: 1,
    status: 'previous&deal',
    stock: 1000,
  },
  {
    _id: 4,
    name: 'Orange Indian (± 50 gm) 1 kg',
    description: '',
    price: 199,
    original_price: 275,
    save: '20%',
    bundle: '1 kg',
    imageUrl:
      'https://chaldn.com/_mpimage/orange-indian-50-gm-1-kg?src=https%3A%2F%2Feggyolk.chaldal.com%2Fapi%2FPicture%2FRaw%3FpictureId%3D126157&q=best&v=1&m=400&webp=1',
    category: 'Food',
    quantity: 1,
    status: 'previous&deal',
    stock: 1000,
  },
  {
    _id: 5,
    name: 'Hosen Mushroom Choice Whole Can 425 gm',
    description: '',
    price: 179,
    original_price: 275,
    save: '20%',
    bundle: '300 gm',
    imageUrl:
      'https://chaldn.com/_mpimage/hosen-mushroom-choice-whole-can-425-gm?src=https%3A%2F%2Feggyolk.chaldal.com%2Fapi%2FPicture%2FRaw%3FpictureId%3D123243&q=best&v=1&m=400&webp=1',
    category: 'Food',
    quantity: 1,
    status: 'previous&deal',
    stock: 1000,
  },
  {
    _id: 6,
    name: 'Finis Ozol Liquid Floor Cleaner Lemon 500 ml (Buy 1 Get 1 Free) 2 pcs',
    description: '',
    price: 149,
    original_price: 175,
    save: '10%',
    bundle: '2 pcs',
    imageUrl:
      'https://chaldn.com/_mpimage/finis-ozol-liquid-floor-cleaner-lemon-500-ml-buy-1-get-1-free-2-pcs?src=https%3A%2F%2Feggyolk.chaldal.com%2Fapi%2FPicture%2FRaw%3FpictureId%3D126997&q=best&v=1&m=400&webp=1',
    category: 'Food',
    quantity: 1,
    status: 'previous&deal',
    stock: 1000,
  },
];

export default previousDeals;
